# Gunakan image dasar yang berisi Python
FROM python:3.9-slim

# Set lingkungan kerja di dalam container
WORKDIR /app

# Salin requirements.txt ke dalam container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Salin seluruh kode aplikasi ke dalam container
COPY . .

# Jalankan aplikasi Streamlit
CMD ["streamlit", "run", "Home.py", "--server.port=8080", "--server.address=0.0.0.0"]